name: Build and Deploy Fundraiser App

on:
  release: 
    types: [published]
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - run: rustc --version
    
    - uses: actions/checkout@v4
    
    - name: Install Trunk
      run: curl -L https://github.com/trunk-rs/trunk/releases/download/v0.21.4/trunk-x86_64-unknown-linux-musl.tar.gz | tar -xzvf -
    - run: ./trunk --version
    
    - name: Install Rust WASM Target
      run: rustup target add wasm32-unknown-unknown

    - name: Build
      run: ./trunk build --release

    - name: Deploy
    - uses: jsmrcaga/action-netlify-deploy@master
      with:
        NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
        NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        NETLIFY_DEPLOY_MESSAGE: "Prod deploy v${{ github.ref }}"
        NETLIFY_DEPLOY_TO_PROD: true
