name: Build and Deploy Fundraiser App

on:
  release: 
    types: [created]
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - run: rustc --version
    
    - uses: actions/checkout@v4
    
    - name: Install Trunk
      run: curl -L https://github.com/trunk-rs/trunk/releases/download/v0.21.4/trunk-x86_64-unknown-linux-musl.tar.gz | tar -xzvf -
    - run: ./trunk --version
    
    - name: Install Rust WASM Target
      run: rustup target add wasm32-unknown-unknown

    - name: Build
      run: ./trunk build --release
